DROP USER IF EXISTS 'root'@'_gateway';
DROP USER IF EXISTS 'root'@'%';

CREATE SCHEMA IF NOT EXISTS test;

CREATE USER 'root'@'%' IDENTIFIED BY 'Passw0rd1!';
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;

FLUSH PRIVILEGES;